### PR TITLE
fix: error when trying to save mock request file that doesn't exist

### LINKED ISSUE #10: Error when trying to save mock request file that doesn't exist
When executing the command "WRITE_MOCK=true yarn es scripts/test.ts", if the mock-requests.json file does not exist, an error message is displayed. However, the command also creates the file.

Error message:
```sh
> WRITE_MOCK=true yarn es scripts/test.ts

$ node -r esbuild-register -r node-fetch scripts/test.ts
{
  err: [Error: ENOENT: no such file or directory, open '/home/user/github/apiWithLog/mock-requests.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/user/github/apiWithLog/mock-requests.json'
  }
}
saved to /home/user/github/apiWithLog/mock-requests.json
```

### PR DESCRIPTION
**Pull request by nogw**
# Description

As mentioned in issue #10, if the file "mock-requests.json" does not exist and you run the command "WRITE_MOCK=true yarn es scripts/test.ts", an error message will be shown, however, the file is created in any case

# Changes

- Add a simple check inside the try-catch block to determine if the error is due to the file not existing.

# Related Issues

* Closes #10

### CODE REVIEW

File: src/apiCache.ts [hunk 1]
```diff
@@ -49,8 +49,10 @@ export const saveRequestMock = async (
 
     console.log(dataString);
   } catch (err) {
-    // eslint-disable-next-line
-    console.log({ err });
+    if (err && err.code !== 'ENOENT') {
+      // eslint-disable-next-line
+      console.log({ err });
+    }
```
Comment (edumaciel10) [inline src/apiCache.ts]: I think that this not is the best solution for your problem
Try to find the root cause

**Review by edumaciel10 — APPROVED** [review]

**Review by daniloab — APPROVED** [review]
hi @nogw thanks for the pull request

can you also add an improvement to create the mock JSON file when it does not exist before saving it?

**Review by fersilva16 — CHANGES_REQUESTED** [review]
Check if the file exists with `fs.existsSync` instead

**Review by fersilva16 — APPROVED** [review]

**Review by edumaciel10 — CHANGES_REQUESTED** [review]
check the fs opening of writemock

**Comment by nogw** [comment]
done, using `fs.existsSync` and creating a empty file instead of ignoring the error

**Review by fersilva16 — APPROVED** [review]

**Review by edumaciel10 — APPROVED** [review]
Nice! Good fix
